### ISSUE TITLE
What are the use cases for tokenizer library?

### ISSUE THREAD

**Issue by sunpietro** [csstools/tokenizer#3]
I'm wondering what can I use it for? The description in repo is not very helpful.

**Comment by jonathantneal** [comment]
Thanks for asking. I will improve the README to describe what the tokenizer can be used for and not just what it does.

While I would need more time to think of how I want to phrase it — a css tokenizer is useful for extracting meaningful data and values from a CSS file, or for preparing a CSS file to be parsed for the purposes of validity checks, transformations, and similarly, polyfills.

The real explanation should include examples of the claims in action, so that people can understand it on its merits. However, as the README already says, this tool is intended to be used by other tools on the front and back end, and it’s not something the average developer wants — they probably want the tool (the validator, the transformer) that uses this tool.

**Comment by jonathantneal** [comment]
I’ve done some work to improve the README, and I’ve also changed the shape of a token from an array to an object.

```js
import { tokenize } from '@csstools/tokenizer'

for (const token of tokenize(cssText)) {
  console.log(token) // logs an individual CSSToken
}
```

```ts
interface CSSToken {
  /** Position in the string at which the token was retrieved. */
  tick: number

  /** Number identifying the kind of token. */
  type:
    | 1 // Symbol
    | 2 // Comment
    | 3 // Space
    | 4 // Word
    | 5 // Action
    | 6 // Atword
    | 7 // Hash
    | 8 // String
    | 9 // Number
  
  /** Character code (when a Symbol, otherwise -1) */
  code: number

  /** Lead, like the opening of a comment or the quotation mark of a string. */
  lead: string,

  /** Data, like the numbers before a unit, or the letters after an at-sign. */
  data: string,

  /** Tail, like the unit of a number, or the closing of a comment. */
  tail: string,
}
```

— [README.md](https://github.com/csstools/tokenizer/tree/c71aa6a20a908b9e85f17d21c9e78d6ba5315458#how-it-works)
